#ifndef NEOEGGSHELL_REDIRACTION_H
#define NEOEGGSHELL_REDIRACTION_H
#include <cstdio>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <cstring>
#include <vector>
void pipeTester();
#endif //NEOEGGSHELL_REDIRACTION_H
